os: linux
dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - pypy

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - pip install -r requirements.txt
  - pip install pytest==5.4.3 pytest-cov==2.10.1 codecov==2.1.10 twine wheel

script:
  - pytest --cov=scake --cov-report=xml -v

after_success:
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    branch: release
